// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/radiophysiker/microservices-homework/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) PayOrder(ctx context.Context, userUUID string, orderUUID string, paymentMethod v1.PaymentMethod) (string, error) {
	ret := _mock.Called(ctx, userUUID, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, v1.PaymentMethod) (string, error)); ok {
		return returnFunc(ctx, userUUID, orderUUID, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, v1.PaymentMethod) string); ok {
		r0 = returnFunc(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, v1.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - orderUUID string
//   - paymentMethod v1.PaymentMethod
func (_e *MockPaymentService_Expecter) PayOrder(ctx interface{}, userUUID interface{}, orderUUID interface{}, paymentMethod interface{}) *MockPaymentService_PayOrder_Call {
	return &MockPaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, userUUID, orderUUID, paymentMethod)}
}

func (_c *MockPaymentService_PayOrder_Call) Run(run func(ctx context.Context, userUUID string, orderUUID string, paymentMethod v1.PaymentMethod)) *MockPaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 v1.PaymentMethod
		if args[3] != nil {
			arg3 = args[3].(v1.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) Return(s string, err error) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, userUUID string, orderUUID string, paymentMethod v1.PaymentMethod) (string, error)) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
