// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/v1/order.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/radiophysiker/microservices-homework/week1/shared/pkg/proto/payment/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Событие OrderPaid публикуется OrderService после успешной оплаты заказа
type OrderPaid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор события (для идемпотентности)
	EventUuid string `protobuf:"bytes,1,opt,name=event_uuid,proto3" json:"event_uuid,omitempty"`
	// Идентификатор оплаченного заказа
	OrderUuid string `protobuf:"bytes,2,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	// Идентификатор пользователя
	UserUuid string `protobuf:"bytes,3,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	// Способ оплаты (в JSON сериализуется как строка, значение из PaymentMethod enum)
	PaymentMethod v1.PaymentMethod `protobuf:"varint,4,opt,name=payment_method,proto3,enum=payment.v1.PaymentMethod" json:"payment_method,omitempty"`
	// Идентификатор транзакции, сгенерированный в результате оплаты
	TransactionUuid string `protobuf:"bytes,5,opt,name=transaction_uuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPaid) Reset() {
	*x = OrderPaid{}
	mi := &file_events_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaid) ProtoMessage() {}

func (x *OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaid.ProtoReflect.Descriptor instead.
func (*OrderPaid) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaid) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderPaid) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderPaid) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderPaid) GetPaymentMethod() v1.PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return v1.PaymentMethod(0)
}

func (x *OrderPaid) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// Событие ShipAssembled публикуется AssemblyService после завершения сборки корабля
type ShipAssembled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор события (для идемпотентности)
	EventUuid string `protobuf:"bytes,1,opt,name=event_uuid,proto3" json:"event_uuid,omitempty"`
	// Идентификатор собранного заказа
	OrderUuid string `protobuf:"bytes,2,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	// Идентификатор пользователя
	UserUuid string `protobuf:"bytes,3,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	// Время (в секундах), потраченное на сборку корабля
	BuildTimeSec  int64 `protobuf:"varint,4,opt,name=build_time_sec,proto3" json:"build_time_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipAssembled) Reset() {
	*x = ShipAssembled{}
	mi := &file_events_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipAssembled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipAssembled) ProtoMessage() {}

func (x *ShipAssembled) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipAssembled.ProtoReflect.Descriptor instead.
func (*ShipAssembled) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *ShipAssembled) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *ShipAssembled) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *ShipAssembled) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ShipAssembled) GetBuildTimeSec() int64 {
	if x != nil {
		return x.BuildTimeSec
	}
	return 0
}

var File_events_v1_order_proto protoreflect.FileDescriptor

const file_events_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/order.proto\x12\tevents.v1\x1a\x17validate/validate.proto\x1a\x18payment/v1/payment.proto\"\x80\x02\n" +
	"\tOrderPaid\x12(\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"event_uuid\x12(\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"order_uuid\x12&\n" +
	"\tuser_uuid\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tuser_uuid\x12A\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x19.payment.v1.PaymentMethodR\x0epayment_method\x124\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x10transaction_uuid\"\xb3\x01\n" +
	"\rShipAssembled\x12(\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"event_uuid\x12(\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"order_uuid\x12&\n" +
	"\tuser_uuid\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tuser_uuid\x12&\n" +
	"\x0ebuild_time_sec\x18\x04 \x01(\x03R\x0ebuild_time_secBLZJgithub.com/radiophysiker/microservices-homework/shared/pkg/proto/events/v1b\x06proto3"

var (
	file_events_v1_order_proto_rawDescOnce sync.Once
	file_events_v1_order_proto_rawDescData []byte
)

func file_events_v1_order_proto_rawDescGZIP() []byte {
	file_events_v1_order_proto_rawDescOnce.Do(func() {
		file_events_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)))
	})
	return file_events_v1_order_proto_rawDescData
}

var file_events_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_v1_order_proto_goTypes = []any{
	(*OrderPaid)(nil),     // 0: events.v1.OrderPaid
	(*ShipAssembled)(nil), // 1: events.v1.ShipAssembled
	(v1.PaymentMethod)(0), // 2: payment.v1.PaymentMethod
}
var file_events_v1_order_proto_depIdxs = []int32{
	2, // 0: events.v1.OrderPaid.payment_method:type_name -> payment.v1.PaymentMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_order_proto_init() }
func file_events_v1_order_proto_init() {
	if File_events_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_order_proto_goTypes,
		DependencyIndexes: file_events_v1_order_proto_depIdxs,
		MessageInfos:      file_events_v1_order_proto_msgTypes,
	}.Build()
	File_events_v1_order_proto = out.File
	file_events_v1_order_proto_goTypes = nil
	file_events_v1_order_proto_depIdxs = nil
}
