// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/v1/order.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	v1 "github.com/radiophysiker/microservices-homework/week1/shared/pkg/proto/payment/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = v1.PaymentMethod(0)
)

// define the regex for a UUID once up-front
var _order_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OrderPaid with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderPaid) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPaid with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderPaidMultiError, or nil
// if none found.
func (m *OrderPaid) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPaid) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetEventUuid()); err != nil {
		err = OrderPaidValidationError{
			field:  "EventUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetOrderUuid()); err != nil {
		err = OrderPaidValidationError{
			field:  "OrderUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserUuid()); err != nil {
		err = OrderPaidValidationError{
			field:  "UserUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PaymentMethod

	if err := m._validateUuid(m.GetTransactionUuid()); err != nil {
		err = OrderPaidValidationError{
			field:  "TransactionUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderPaidMultiError(errors)
	}

	return nil
}

func (m *OrderPaid) _validateUuid(uuid string) error {
	if matched := _order_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderPaidMultiError is an error wrapping multiple validation errors returned
// by OrderPaid.ValidateAll() if the designated constraints aren't met.
type OrderPaidMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPaidMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPaidMultiError) AllErrors() []error { return m }

// OrderPaidValidationError is the validation error returned by
// OrderPaid.Validate if the designated constraints aren't met.
type OrderPaidValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPaidValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPaidValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPaidValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPaidValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPaidValidationError) ErrorName() string { return "OrderPaidValidationError" }

// Error satisfies the builtin error interface
func (e OrderPaidValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPaid.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPaidValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPaidValidationError{}

// Validate checks the field values on ShipAssembled with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShipAssembled) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShipAssembled with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShipAssembledMultiError, or
// nil if none found.
func (m *ShipAssembled) ValidateAll() error {
	return m.validate(true)
}

func (m *ShipAssembled) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetEventUuid()); err != nil {
		err = ShipAssembledValidationError{
			field:  "EventUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetOrderUuid()); err != nil {
		err = ShipAssembledValidationError{
			field:  "OrderUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserUuid()); err != nil {
		err = ShipAssembledValidationError{
			field:  "UserUuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for BuildTimeSec

	if len(errors) > 0 {
		return ShipAssembledMultiError(errors)
	}

	return nil
}

func (m *ShipAssembled) _validateUuid(uuid string) error {
	if matched := _order_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ShipAssembledMultiError is an error wrapping multiple validation errors
// returned by ShipAssembled.ValidateAll() if the designated constraints
// aren't met.
type ShipAssembledMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShipAssembledMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShipAssembledMultiError) AllErrors() []error { return m }

// ShipAssembledValidationError is the validation error returned by
// ShipAssembled.Validate if the designated constraints aren't met.
type ShipAssembledValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShipAssembledValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShipAssembledValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShipAssembledValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShipAssembledValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShipAssembledValidationError) ErrorName() string { return "ShipAssembledValidationError" }

// Error satisfies the builtin error interface
func (e ShipAssembledValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShipAssembled.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShipAssembledValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShipAssembledValidationError{}
