// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryGRPCConfig creates a new instance of MockInventoryGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryGRPCConfig {
	mock := &MockInventoryGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryGRPCConfig is an autogenerated mock type for the InventoryGRPCConfig type
type MockInventoryGRPCConfig struct {
	mock.Mock
}

type MockInventoryGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryGRPCConfig) EXPECT() *MockInventoryGRPCConfig_Expecter {
	return &MockInventoryGRPCConfig_Expecter{mock: &_m.Mock}
}

// InventoryAddress provides a mock function for the type MockInventoryGRPCConfig
func (_mock *MockInventoryGRPCConfig) InventoryAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InventoryAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInventoryGRPCConfig_InventoryAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InventoryAddress'
type MockInventoryGRPCConfig_InventoryAddress_Call struct {
	*mock.Call
}

// InventoryAddress is a helper method to define mock.On call
func (_e *MockInventoryGRPCConfig_Expecter) InventoryAddress() *MockInventoryGRPCConfig_InventoryAddress_Call {
	return &MockInventoryGRPCConfig_InventoryAddress_Call{Call: _e.mock.On("InventoryAddress")}
}

func (_c *MockInventoryGRPCConfig_InventoryAddress_Call) Run(run func()) *MockInventoryGRPCConfig_InventoryAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInventoryGRPCConfig_InventoryAddress_Call) Return(s string) *MockInventoryGRPCConfig_InventoryAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInventoryGRPCConfig_InventoryAddress_Call) RunAndReturn(run func() string) *MockInventoryGRPCConfig_InventoryAddress_Call {
	_c.Call.Return(run)
	return _c
}
