// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentGRPCConfig creates a new instance of MockPaymentGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGRPCConfig {
	mock := &MockPaymentGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentGRPCConfig is an autogenerated mock type for the PaymentGRPCConfig type
type MockPaymentGRPCConfig struct {
	mock.Mock
}

type MockPaymentGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentGRPCConfig) EXPECT() *MockPaymentGRPCConfig_Expecter {
	return &MockPaymentGRPCConfig_Expecter{mock: &_m.Mock}
}

// PaymentAddress provides a mock function for the type MockPaymentGRPCConfig
func (_mock *MockPaymentGRPCConfig) PaymentAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PaymentAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPaymentGRPCConfig_PaymentAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentAddress'
type MockPaymentGRPCConfig_PaymentAddress_Call struct {
	*mock.Call
}

// PaymentAddress is a helper method to define mock.On call
func (_e *MockPaymentGRPCConfig_Expecter) PaymentAddress() *MockPaymentGRPCConfig_PaymentAddress_Call {
	return &MockPaymentGRPCConfig_PaymentAddress_Call{Call: _e.mock.On("PaymentAddress")}
}

func (_c *MockPaymentGRPCConfig_PaymentAddress_Call) Run(run func()) *MockPaymentGRPCConfig_PaymentAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentGRPCConfig_PaymentAddress_Call) Return(s string) *MockPaymentGRPCConfig_PaymentAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPaymentGRPCConfig_PaymentAddress_Call) RunAndReturn(run func() string) *MockPaymentGRPCConfig_PaymentAddress_Call {
	_c.Call.Return(run)
	return _c
}
