// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgresConfig creates a new instance of MockPostgresConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresConfig {
	mock := &MockPostgresConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgresConfig is an autogenerated mock type for the PostgresConfig type
type MockPostgresConfig struct {
	mock.Mock
}

type MockPostgresConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresConfig) EXPECT() *MockPostgresConfig_Expecter {
	return &MockPostgresConfig_Expecter{mock: &_m.Mock}
}

// DSN provides a mock function for the type MockPostgresConfig
func (_mock *MockPostgresConfig) DSN() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DSN")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPostgresConfig_DSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DSN'
type MockPostgresConfig_DSN_Call struct {
	*mock.Call
}

// DSN is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) DSN() *MockPostgresConfig_DSN_Call {
	return &MockPostgresConfig_DSN_Call{Call: _e.mock.On("DSN")}
}

func (_c *MockPostgresConfig_DSN_Call) Run(run func()) *MockPostgresConfig_DSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_DSN_Call) Return(s string) *MockPostgresConfig_DSN_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPostgresConfig_DSN_Call) RunAndReturn(run func() string) *MockPostgresConfig_DSN_Call {
	_c.Call.Return(run)
	return _c
}

// PoolMaxConnIdleTime provides a mock function for the type MockPostgresConfig
func (_mock *MockPostgresConfig) PoolMaxConnIdleTime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PoolMaxConnIdleTime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockPostgresConfig_PoolMaxConnIdleTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PoolMaxConnIdleTime'
type MockPostgresConfig_PoolMaxConnIdleTime_Call struct {
	*mock.Call
}

// PoolMaxConnIdleTime is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) PoolMaxConnIdleTime() *MockPostgresConfig_PoolMaxConnIdleTime_Call {
	return &MockPostgresConfig_PoolMaxConnIdleTime_Call{Call: _e.mock.On("PoolMaxConnIdleTime")}
}

func (_c *MockPostgresConfig_PoolMaxConnIdleTime_Call) Run(run func()) *MockPostgresConfig_PoolMaxConnIdleTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConnIdleTime_Call) Return(duration time.Duration) *MockPostgresConfig_PoolMaxConnIdleTime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConnIdleTime_Call) RunAndReturn(run func() time.Duration) *MockPostgresConfig_PoolMaxConnIdleTime_Call {
	_c.Call.Return(run)
	return _c
}

// PoolMaxConnLifetime provides a mock function for the type MockPostgresConfig
func (_mock *MockPostgresConfig) PoolMaxConnLifetime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PoolMaxConnLifetime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockPostgresConfig_PoolMaxConnLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PoolMaxConnLifetime'
type MockPostgresConfig_PoolMaxConnLifetime_Call struct {
	*mock.Call
}

// PoolMaxConnLifetime is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) PoolMaxConnLifetime() *MockPostgresConfig_PoolMaxConnLifetime_Call {
	return &MockPostgresConfig_PoolMaxConnLifetime_Call{Call: _e.mock.On("PoolMaxConnLifetime")}
}

func (_c *MockPostgresConfig_PoolMaxConnLifetime_Call) Run(run func()) *MockPostgresConfig_PoolMaxConnLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConnLifetime_Call) Return(duration time.Duration) *MockPostgresConfig_PoolMaxConnLifetime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConnLifetime_Call) RunAndReturn(run func() time.Duration) *MockPostgresConfig_PoolMaxConnLifetime_Call {
	_c.Call.Return(run)
	return _c
}

// PoolMaxConns provides a mock function for the type MockPostgresConfig
func (_mock *MockPostgresConfig) PoolMaxConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PoolMaxConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockPostgresConfig_PoolMaxConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PoolMaxConns'
type MockPostgresConfig_PoolMaxConns_Call struct {
	*mock.Call
}

// PoolMaxConns is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) PoolMaxConns() *MockPostgresConfig_PoolMaxConns_Call {
	return &MockPostgresConfig_PoolMaxConns_Call{Call: _e.mock.On("PoolMaxConns")}
}

func (_c *MockPostgresConfig_PoolMaxConns_Call) Run(run func()) *MockPostgresConfig_PoolMaxConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConns_Call) Return(n int32) *MockPostgresConfig_PoolMaxConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPostgresConfig_PoolMaxConns_Call) RunAndReturn(run func() int32) *MockPostgresConfig_PoolMaxConns_Call {
	_c.Call.Return(run)
	return _c
}

// PoolMinConns provides a mock function for the type MockPostgresConfig
func (_mock *MockPostgresConfig) PoolMinConns() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PoolMinConns")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockPostgresConfig_PoolMinConns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PoolMinConns'
type MockPostgresConfig_PoolMinConns_Call struct {
	*mock.Call
}

// PoolMinConns is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) PoolMinConns() *MockPostgresConfig_PoolMinConns_Call {
	return &MockPostgresConfig_PoolMinConns_Call{Call: _e.mock.On("PoolMinConns")}
}

func (_c *MockPostgresConfig_PoolMinConns_Call) Run(run func()) *MockPostgresConfig_PoolMinConns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_PoolMinConns_Call) Return(n int32) *MockPostgresConfig_PoolMinConns_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPostgresConfig_PoolMinConns_Call) RunAndReturn(run func() int32) *MockPostgresConfig_PoolMinConns_Call {
	_c.Call.Return(run)
	return _c
}
