// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/order.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статусы заказа
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED     OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID            OrderStatus = 2
	OrderStatus_ORDER_STATUS_CANCELLED       OrderStatus = 3
	OrderStatus_ORDER_STATUS_ASSEMBLED       OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING_PAYMENT",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_CANCELLED",
		4: "ORDER_STATUS_ASSEMBLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":     0,
		"ORDER_STATUS_PENDING_PAYMENT": 1,
		"ORDER_STATUS_PAID":            2,
		"ORDER_STATUS_CANCELLED":       3,
		"ORDER_STATUS_ASSEMBLED":       4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// Способы оплаты
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_UNKNOWN                    PaymentMethod = 1
	PaymentMethod_CARD                       PaymentMethod = 2
	PaymentMethod_SBP                        PaymentMethod = 3
	PaymentMethod_CREDIT_CARD                PaymentMethod = 4
	PaymentMethod_INVESTOR_MONEY             PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "UNKNOWN",
		2: "CARD",
		3: "SBP",
		4: "CREDIT_CARD",
		5: "INVESTOR_MONEY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"UNKNOWN":                    1,
		"CARD":                       2,
		"SBP":                        3,
		"CREDIT_CARD":                4,
		"INVESTOR_MONEY":             5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

// Запрос на создание заказа
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	PartUuids     []string               `protobuf:"bytes,2,rep,name=part_uuids,proto3" json:"part_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateOrderRequest) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

// Ответ создания заказа
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *CreateOrderResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

// Запрос на получение заказа
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// Ответ с информацией о заказе
type GetOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid       string                 `protobuf:"bytes,1,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	UserUuid        string                 `protobuf:"bytes,2,opt,name=user_uuid,proto3" json:"user_uuid,omitempty"`
	PartUuids       []string               `protobuf:"bytes,3,rep,name=part_uuids,proto3" json:"part_uuids,omitempty"`
	TotalPrice      float64                `protobuf:"fixed64,4,opt,name=total_price,proto3" json:"total_price,omitempty"`
	TransactionUuid *string                `protobuf:"bytes,5,opt,name=transaction_uuid,proto3,oneof" json:"transaction_uuid,omitempty"`
	PaymentMethod   *PaymentMethod         `protobuf:"varint,6,opt,name=payment_method,proto3,enum=order.v1.PaymentMethod,oneof" json:"payment_method,omitempty"`
	Status          OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderResponse) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *GetOrderResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetOrderResponse) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

func (x *GetOrderResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *GetOrderResponse) GetTransactionUuid() string {
	if x != nil && x.TransactionUuid != nil {
		return *x.TransactionUuid
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentMethod() PaymentMethod {
	if x != nil && x.PaymentMethod != nil {
		return *x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *GetOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

// Запрос на оплату заказа
type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,2,opt,name=payment_method,proto3,enum=order.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *PayOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

// Ответ оплаты заказа
type PayOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *PayOrderResponse) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// Запрос на отмену заказа
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"f\n" +
	"\x12CreateOrderRequest\x12&\n" +
	"\tuser_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tuser_uuid\x12(\n" +
	"\n" +
	"part_uuids\x18\x02 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\n" +
	"part_uuids\"W\n" +
	"\x13CreateOrderResponse\x12\x1e\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\n" +
	"order_uuid\x12 \n" +
	"\vtotal_price\x18\x02 \x01(\x01R\vtotal_price\";\n" +
	"\x0fGetOrderRequest\x12(\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"order_uuid\"\xe0\x02\n" +
	"\x10GetOrderResponse\x12\x1e\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\n" +
	"order_uuid\x12\x1c\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\tuser_uuid\x12\x1e\n" +
	"\n" +
	"part_uuids\x18\x03 \x03(\tR\n" +
	"part_uuids\x12 \n" +
	"\vtotal_price\x18\x04 \x01(\x01R\vtotal_price\x12/\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tH\x00R\x10transaction_uuid\x88\x01\x01\x12D\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x17.order.v1.PaymentMethodH\x01R\x0epayment_method\x88\x01\x01\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.order.v1.OrderStatusR\x06statusB\x13\n" +
	"\x11_transaction_uuidB\x11\n" +
	"\x0f_payment_method\"\x86\x01\n" +
	"\x0fPayOrderRequest\x12(\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"order_uuid\x12I\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x17.order.v1.PaymentMethodB\b\xfaB\x05\x82\x01\x02\x10\x01R\x0epayment_method\">\n" +
	"\x10PayOrderResponse\x12*\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x10transaction_uuid\">\n" +
	"\x12CancelOrderRequest\x12(\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"order_uuid*\x9c\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_ASSEMBLED\x10\x04*t\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\b\n" +
	"\x04CARD\x10\x02\x12\a\n" +
	"\x03SBP\x10\x03\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x04\x12\x12\n" +
	"\x0eINVESTOR_MONEY\x10\x052\xbd\x03\n" +
	"\fOrderService\x12e\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/orders\x12f\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/orders/{order_uuid}\x12m\n" +
	"\bPayOrder\x12\x19.order.v1.PayOrderRequest\x1a\x1a.order.v1.PayOrderResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/orders/{order_uuid}/pay\x12o\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$\"\"/api/v1/orders/{order_uuid}/cancelBKZIgithub.com/radiophysiker/microservices-homework/shared/pkg/proto/order/v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),            // 0: order.v1.OrderStatus
	(PaymentMethod)(0),          // 1: order.v1.PaymentMethod
	(*CreateOrderRequest)(nil),  // 2: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 3: order.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),     // 4: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),    // 5: order.v1.GetOrderResponse
	(*PayOrderRequest)(nil),     // 6: order.v1.PayOrderRequest
	(*PayOrderResponse)(nil),    // 7: order.v1.PayOrderResponse
	(*CancelOrderRequest)(nil),  // 8: order.v1.CancelOrderRequest
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_order_v1_order_proto_depIdxs = []int32{
	1, // 0: order.v1.GetOrderResponse.payment_method:type_name -> order.v1.PaymentMethod
	0, // 1: order.v1.GetOrderResponse.status:type_name -> order.v1.OrderStatus
	1, // 2: order.v1.PayOrderRequest.payment_method:type_name -> order.v1.PaymentMethod
	2, // 3: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	4, // 4: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	6, // 5: order.v1.OrderService.PayOrder:input_type -> order.v1.PayOrderRequest
	8, // 6: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	3, // 7: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	5, // 8: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	7, // 9: order.v1.OrderService.PayOrder:output_type -> order.v1.PayOrderResponse
	9, // 10: order.v1.OrderService.CancelOrder:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	file_order_v1_order_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		EnumInfos:         file_order_v1_order_proto_enumTypes,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
