// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Merged schema.
// Ref: #
type BadRequestError struct {
	// Merged property.
	Error BadRequestErrorError `json:"error"`
	// Merged property.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *BadRequestError) GetError() BadRequestErrorError {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *BadRequestError) SetError(val BadRequestErrorError) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes() {}
func (*BadRequestError) createOrderRes() {}
func (*BadRequestError) getOrderRes()    {}
func (*BadRequestError) payOrderRes()    {}

// Merged schema.
type BadRequestErrorError string

const (
	BadRequestErrorErrorBadRequest BadRequestErrorError = "bad_request"
)

// AllValues returns all BadRequestErrorError values.
func (BadRequestErrorError) AllValues() []BadRequestErrorError {
	return []BadRequestErrorError{
		BadRequestErrorErrorBadRequest,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BadRequestErrorError) MarshalText() ([]byte, error) {
	switch s {
	case BadRequestErrorErrorBadRequest:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BadRequestErrorError) UnmarshalText(data []byte) error {
	switch BadRequestErrorError(data) {
	case BadRequestErrorErrorBadRequest:
		*s = BadRequestErrorErrorBadRequest
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Merged schema.
// Ref: #
type ConflictError struct {
	// Merged property.
	Error ConflictErrorError `json:"error"`
	// Merged property.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *ConflictError) GetError() ConflictErrorError {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *ConflictError) SetError(val ConflictErrorError) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}
func (*ConflictError) payOrderRes()    {}

// Merged schema.
type ConflictErrorError string

const (
	ConflictErrorErrorConflict ConflictErrorError = "conflict"
)

// AllValues returns all ConflictErrorError values.
func (ConflictErrorError) AllValues() []ConflictErrorError {
	return []ConflictErrorError{
		ConflictErrorErrorConflict,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ConflictErrorError) MarshalText() ([]byte, error) {
	switch s {
	case ConflictErrorErrorConflict:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ConflictErrorError) UnmarshalText(data []byte) error {
	switch ConflictErrorError(data) {
	case ConflictErrorErrorConflict:
		*s = ConflictErrorErrorConflict
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type CreateOrderRequest struct {
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #
type CreateOrderResponse struct {
	// UUID созданного заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Общая стоимость заказа.
	TotalPrice float64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #
type GenericError struct {
	// Код ошибки.
	Error string `json:"error"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *GenericError) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *GenericError) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Merged schema.
// Ref: #
type InternalServerError struct {
	// Merged property.
	Error InternalServerErrorError `json:"error"`
	// Merged property.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *InternalServerError) GetError() InternalServerErrorError {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *InternalServerError) SetError(val InternalServerErrorError) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes() {}
func (*InternalServerError) createOrderRes() {}
func (*InternalServerError) getOrderRes()    {}
func (*InternalServerError) payOrderRes()    {}

// Merged schema.
type InternalServerErrorError string

const (
	InternalServerErrorErrorInternalServerError InternalServerErrorError = "internal_server_error"
)

// AllValues returns all InternalServerErrorError values.
func (InternalServerErrorError) AllValues() []InternalServerErrorError {
	return []InternalServerErrorError{
		InternalServerErrorErrorInternalServerError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s InternalServerErrorError) MarshalText() ([]byte, error) {
	switch s {
	case InternalServerErrorErrorInternalServerError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *InternalServerErrorError) UnmarshalText(data []byte) error {
	switch InternalServerErrorError(data) {
	case InternalServerErrorErrorInternalServerError:
		*s = InternalServerErrorErrorInternalServerError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilOrderDtoPaymentMethod returns new NilOrderDtoPaymentMethod with value set to v.
func NewNilOrderDtoPaymentMethod(v OrderDtoPaymentMethod) NilOrderDtoPaymentMethod {
	return NilOrderDtoPaymentMethod{
		Value: v,
	}
}

// NilOrderDtoPaymentMethod is nullable OrderDtoPaymentMethod.
type NilOrderDtoPaymentMethod struct {
	Value OrderDtoPaymentMethod
	Null  bool
}

// SetTo sets value to v.
func (o *NilOrderDtoPaymentMethod) SetTo(v OrderDtoPaymentMethod) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilOrderDtoPaymentMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilOrderDtoPaymentMethod) SetToNull() {
	o.Null = true
	var v OrderDtoPaymentMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilOrderDtoPaymentMethod) Get() (v OrderDtoPaymentMethod, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilOrderDtoPaymentMethod) Or(d OrderDtoPaymentMethod) OrderDtoPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #
type NotFoundError struct {
	// Merged property.
	Error NotFoundErrorError `json:"error"`
	// Merged property.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *NotFoundError) GetError() NotFoundErrorError {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *NotFoundError) SetError(val NotFoundErrorError) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes() {}
func (*NotFoundError) getOrderRes()    {}
func (*NotFoundError) payOrderRes()    {}

// Merged schema.
type NotFoundErrorError string

const (
	NotFoundErrorErrorNotFound NotFoundErrorError = "not_found"
)

// AllValues returns all NotFoundErrorError values.
func (NotFoundErrorError) AllValues() []NotFoundErrorError {
	return []NotFoundErrorError{
		NotFoundErrorErrorNotFound,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NotFoundErrorError) MarshalText() ([]byte, error) {
	switch s {
	case NotFoundErrorErrorNotFound:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NotFoundErrorError) UnmarshalText(data []byte) error {
	switch NotFoundErrorError(data) {
	case NotFoundErrorErrorNotFound:
		*s = NotFoundErrorErrorNotFound
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type OrderDto struct {
	// UUID заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей в заказе.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Общая стоимость заказа.
	TotalPrice float64 `json:"total_price"`
	// UUID транзакции оплаты (если заказ оплачен).
	TransactionUUID OptNilUUID `json:"transaction_uuid"`
	// Способ оплаты (если заказ оплачен).
	PaymentMethod *NilOrderDtoPaymentMethod `json:"payment_method"`
	Status        OrderStatus               `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderDto) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderDto) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderDto) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderDto) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderDto) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderDto) GetPaymentMethod() *NilOrderDtoPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderDto) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderDto) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderDto) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderDto) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderDto) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderDto) SetPaymentMethod(val *NilOrderDtoPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*OrderDto) getOrderRes() {}

// Merged schema.
type OrderDtoPaymentMethod string

const (
	OrderDtoPaymentMethodUNKNOWN       OrderDtoPaymentMethod = "UNKNOWN"
	OrderDtoPaymentMethodCARD          OrderDtoPaymentMethod = "CARD"
	OrderDtoPaymentMethodSBP           OrderDtoPaymentMethod = "SBP"
	OrderDtoPaymentMethodCREDITCARD    OrderDtoPaymentMethod = "CREDIT_CARD"
	OrderDtoPaymentMethodINVESTORMONEY OrderDtoPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all OrderDtoPaymentMethod values.
func (OrderDtoPaymentMethod) AllValues() []OrderDtoPaymentMethod {
	return []OrderDtoPaymentMethod{
		OrderDtoPaymentMethodUNKNOWN,
		OrderDtoPaymentMethodCARD,
		OrderDtoPaymentMethodSBP,
		OrderDtoPaymentMethodCREDITCARD,
		OrderDtoPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderDtoPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderDtoPaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderDtoPaymentMethodCARD:
		return []byte(s), nil
	case OrderDtoPaymentMethodSBP:
		return []byte(s), nil
	case OrderDtoPaymentMethodCREDITCARD:
		return []byte(s), nil
	case OrderDtoPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderDtoPaymentMethod) UnmarshalText(data []byte) error {
	switch OrderDtoPaymentMethod(data) {
	case OrderDtoPaymentMethodUNKNOWN:
		*s = OrderDtoPaymentMethodUNKNOWN
		return nil
	case OrderDtoPaymentMethodCARD:
		*s = OrderDtoPaymentMethodCARD
		return nil
	case OrderDtoPaymentMethodSBP:
		*s = OrderDtoPaymentMethodSBP
		return nil
	case OrderDtoPaymentMethodCREDITCARD:
		*s = OrderDtoPaymentMethodCREDITCARD
		return nil
	case OrderDtoPaymentMethodINVESTORMONEY:
		*s = OrderDtoPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Статус заказа.
// Ref: #
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #
type PayOrderResponse struct {
	// UUID транзакции оплаты.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Способ оплаты.
// Ref: #
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
